@startuml

abstract class AbstractProduct
class ProductA
class ProductB
class Factory {
    + newInstance(): AbstractProduct
}

ProductA --|> AbstractProduct
ProductB --|> AbstractProduct

Factory ..> AbstractProduct

@enduml